CREATE TABLE IF NOT EXISTS Game (
    game_id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL UNIQUE,
    result BOOLEAN
);

CREATE TABLE IF NOT EXISTS Guesses (
    guess_id INTEGER PRIMARY KEY AUTOINCREMENT,
    game_id INTEGER,
    guess TEXT NOT NULL,
    feedback TEXT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (game_id) REFERENCES Game(game_id)
);